name: getx_scaffold
description: "GetX Scaffold is a comprehensive rapid development template built on the GetX framework and several commonly used plugins"
version: 0.1.1
homepage: https://github.com/Kxmrg
repository: https://github.com/Kxmrg/flutter_getx_scaffold
issue_tracker: https://github.com/Kxmrg/flutter_getx_scaffold/issues

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  crypto: ^3.0.3
  convert: ^3.1.1
  decimal: ^3.0.2
  rational: ^2.2.3
  get: ^4.6.6
  dio: ^5.5.0+1
  flutter_screenutil: ^5.9.3
  flutter_easyloading: ^3.0.5
  connectivity_plus: ^6.0.3
  event_bus: ^2.0.0
  shared_preferences: ^2.2.3
  encrypt: ^5.0.3
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  badges: ^3.1.2
  extended_image: ^8.2.1
  flutter_spinkit: ^5.2.1
  lottie: ^3.1.2
  modal_bottom_sheet: ^3.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/icons/
    - assets/lottie/
    - assets/svgs/

  fonts:
    - family: antdIcon
      fonts:
        - asset: assets/fonts/icon-antd.ttf
